"""add_blocking_reason_title_and_field_reports

Revision ID: 6229bd540e5d
Revises: 9daddb4b40be
Create Date: 2026-05-18 11:52:46.856312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6229bd540e5d'
down_revision: Union[str, None] = '9daddb4b40be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_field_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_field_reports_product_id'), 'product_field_reports', ['product_id'], unique=False)
    op.add_column('products', sa.Column('blocking_reason_title', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'blocking_reason_title')
    op.drop_index(op.f('ix_product_field_reports_product_id'), table_name='product_field_reports')
    op.drop_table('product_field_reports')
    # ### end Alembic commands ###
