"""add_unreserve_operations

Revision ID: 88f77f5af168
Revises: d0d4ca87a326
Create Date: 2026-05-24 12:56:45.200813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88f77f5af168'
down_revision: Union[str, None] = 'd0d4ca87a326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unreserve_operations',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unreserve_operations')
    # ### end Alembic commands ###
