"""add_sku_fields

Revision ID: 9daddb4b40be
Revises: a3c9e1d72b45
Create Date: 2026-05-16 17:20:04.387176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9daddb4b40be'
down_revision: Union[str, None] = 'a3c9e1d72b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.BigInteger(), nullable=True))
    op.add_column('skus', sa.Column('discount', sa.BigInteger(), nullable=False))
    op.add_column('skus', sa.Column('reserved_quantity', sa.Integer(), nullable=False))
    op.add_column('skus', sa.Column('article', sa.String(length=255), nullable=True))
    op.add_column('skus', sa.Column('image', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'image')
    op.drop_column('skus', 'article')
    op.drop_column('skus', 'reserved_quantity')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
