"""empty message

Revision ID: d0d4ca87a326
Revises: 6229bd540e5d
Create Date: 2026-05-18 17:00:27.679401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0d4ca87a326'
down_revision: Union[str, None] = '6229bd540e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve_operations',
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve_operations')
    # ### end Alembic commands ###
